---
- name: Install tomcat
  hosts: appservers
  become: true
  tasks:
    - name: Upadte the latest version of Apache
      ansible.builtin.yum:
        name: "*"
        state: latest
    - name: enable java application
      ansible.builtin.command: amazon-linux-extras enable java-openjdk11
    - name: install java application
      ansible.builtin.yum:
        name: java-11-openjdk
        state: latest
    - name: create tomcat group
      ansible.builtin.group:
        name: group_tomcat
        state: present
        system: true
    - name: create tomcat user
      ansible.builtin.user:
        name: user_tomcat
        state: present
        system: true
        group: group_tomcat
    - name: Install wget package
      ansible.builtin.yum:
        name: wget
        state: latest
    - name: Download tomcat
      ansible.builtin.command: wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.72/bin/apache-tomcat-9.0.72.tar.gz
    - name: Unzip tomcat zip file
      ansible.builtin.unarchive:
        src: /home/ec2-user/apache-tomcat-9.0.72.tar.gz
        dest: /home/ec2-user/
        remote_src: yes
    - name: copy tomcat to /usr/share
      ansible.builtin.copy:
        src: /home/ec2-user/apache-tomcat-9.0.72
        dest: /usr/share/
        remote_src: yes
        owner: user_tomcat
        group: group_tomcat
    - name: create symbolic link
      ansible.builtin.file:
        src: /usr/share/apache-tomcat-9.0.72
        dest: /usr/share/user_tomcat
        state: link
        owner: user_tomcat
        group: group_tomcat
    - name: copy tomcat service
      ansible.builtin.copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
    - name: start tomcat service
      ansible.builtin.systemd:
        name: tomcat.service
        enabled: yes
        daemon_reload: true
        state: started